### ISSUE TITLE
`FileNotFoundError: [Errno 2] No such file or directory: '/home/yongjiang.jy/.flair/datasets/wnut17_bertscore_eos_doc_full'`

### ISSUE THREAD

**Issue by ciaochiaociao** [Alibaba-NLP/CLNER#4]
Hello, it seems that the code also needs the file wnut17_bertscore_eos_doc_full from the above path. Isn't it automatically generated by your code? Or how should I do to get this file? Thank you.

```
Traceback (most recent call last):
  File "train.py", line 83, in <module>
    config = ConfigParser(config,all=args.all,zero_shot=args.zeroshot,other_shot=args.other,predict=args.predict)
  File "/mnt/nluuser/cwhsu/workspace/CLNER/flair/config_parser.py", line 62, in __init__
    self.corpus: ListCorpus=self.get_corpus
  File "/mnt/nluuser/cwhsu/workspace/CLNER/flair/config_parser.py", line 330, in get_corpus
    current_dataset=getattr(datasets,corpus_name)(**self.config[self.target][corpus])
  File "/mnt/nluuser/cwhsu/workspace/CLNER/flair/datasets.py", line 59, in __init__
    for file in data_folder.iterdir():
  File "/home/cwhsu/anaconda3/envs/CLNER4/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/home/cwhsu/anaconda3/envs/CLNER4/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/yongjiang.jy/.flair/datasets/wnut17_bertscore_eos_doc_full'
```

**Comment by wangxinyu0922** [comment]
Hi, you can find the download link of the datasets in [README.md](https://github.com/Alibaba-NLP/CLNER#datasets). After you download and unzip the datasets, modify the path to the dataset in the config file (`data_folder`). For example:
```
ner:
  ColumnCorpus-WNUTDOCFULL:
    column_format:
      0: text
      1: ner
    data_folder: wnut17_bertscore_eos_doc_full
    tag_to_bioes: ner
  Corpus: ColumnCorpus-WNUTDOCFULL
```

**Comment by ciaochiaociao** [comment]
Thank you. I did not notice that the file link in REAMDE.md includes the dataset and the Google retrieved texts. I appreciate your help. And it seems to work regardless of the Out-of-the-memory error. I will try to use a larger GPU.
